# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\x0f\x66orgebot.engine\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"7\n\x0bOrientation\x12\x0b\n\x03yaw\x18\x01 \x01(\x02\x12\r\n\x05pitch\x18\x02 \x01(\x02\x12\x0c\n\x04roll\x18\x03 \x01(\x02\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\t\n\x01w\x18\x04 \x01(\x02\"\xa9\x01\n\x04Ovis\x12\x31\n\x0borientation\x18\x01 \x01(\x0b\x32\x1c.forgebot.engine.Orientation\x12*\n\x08position\x18\x02 \x01(\x0b\x32\x18.forgebot.engine.Vector3\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x32\n\x10tcp_offset_local\x18\x04 \x01(\x0b\x32\x18.forgebot.engine.Vector3\"1\n\nJointState\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01q\x18\x02 \x01(\x02\x12\x0c\n\x04qdot\x18\x03 \x01(\x02\"s\n\x06\x45\x45Pose\x12\x0b\n\x03tip\x18\x01 \x01(\t\x12*\n\x08position\x18\x02 \x01(\x0b\x32\x18.forgebot.engine.Vector3\x12\x30\n\x0borientation\x18\x03 \x01(\x0b\x32\x1b.forgebot.engine.Quaternion\"\x81\x01\n\nSolverDiag\x12\r\n\x05iters\x18\x01 \x01(\x05\x12\x14\n\x0cpos_residual\x18\x02 \x01(\x02\x12\x14\n\x0crot_residual\x18\x03 \x01(\x02\x12\x11\n\tconverged\x18\x04 \x01(\x08\x12\x15\n\rcollision_hit\x18\x05 \x01(\x08\x12\x0e\n\x06target\x18\x06 \x01(\t\"\x95\x01\n\x0bStateUpdate\x12\t\n\x01t\x18\x01 \x01(\x01\x12+\n\x06joints\x18\x02 \x03(\x0b\x32\x1b.forgebot.engine.JointState\x12#\n\x02\x65\x65\x18\x03 \x01(\x0b\x32\x17.forgebot.engine.EEPose\x12)\n\x04\x64iag\x18\x04 \x01(\x0b\x32\x1b.forgebot.engine.SolverDiagb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VECTOR3']._serialized_start=35
  _globals['_VECTOR3']._serialized_end=77
  _globals['_ORIENTATION']._serialized_start=79
  _globals['_ORIENTATION']._serialized_end=134
  _globals['_QUATERNION']._serialized_start=136
  _globals['_QUATERNION']._serialized_end=192
  _globals['_OVIS']._serialized_start=195
  _globals['_OVIS']._serialized_end=364
  _globals['_JOINTSTATE']._serialized_start=366
  _globals['_JOINTSTATE']._serialized_end=415
  _globals['_EEPOSE']._serialized_start=417
  _globals['_EEPOSE']._serialized_end=532
  _globals['_SOLVERDIAG']._serialized_start=535
  _globals['_SOLVERDIAG']._serialized_end=664
  _globals['_STATEUPDATE']._serialized_start=667
  _globals['_STATEUPDATE']._serialized_end=816
# @@protoc_insertion_point(module_scope)
